name: GitHub CI

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: 0 20 * * 0

jobs:
  generate-jobs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: [golang, python]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check ${{ matrix.app }}
        run: |
          commit_message="build(${{ matrix.app }}): bump ${{ matrix.app }} to latest"
          cd ${{ matrix.app }}
          chmod +x *.sh
          ./update.sh
          cd ..
          git status
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git commit -am "${commit_message}" || exit 0
          git push origin HEAD:main
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}