name: Check Images

on:
  workflow_dispatch:
  schedule:
    - cron: 0 1 * * *

jobs:
  check-python:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        suite: ['trixie', 'slim-trixie', 'alpine']
        app: ['python']
        version: ['3.9', '3.10', '3.11', '3.12', '3.13']

    steps:
    - uses: docker/setup-qemu-action@v3
    - uses: docker/setup-buildx-action@v3

    - name: Check ${{ matrix.app }}:${{ matrix.version }}-${{ matrix.suite }}
      run: |
        docker run --rm --platform linux/loong64 ghcr.io/${{ github.repository_owner }}/${{ matrix.app }}:${{ matrix.version }}-${{ matrix.suite }} python --version

  check-golang:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        suite: ['trixie', 'alpine']
        app: ['golang']
        version: ['1.22', '1.23']

    steps:
    - uses: docker/setup-qemu-action@v3
    - uses: docker/setup-buildx-action@v3

    - name: Check ${{ matrix.app }}:${{ matrix.version }}-${{ matrix.suite }}
      run: |
        docker run --rm --platform linux/loong64 ghcr.io/${{ github.repository_owner }}/${{ matrix.app }}:${{ matrix.version }}-${{ matrix.suite }} go version

  check-node:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        suite: ['trixie', 'trixie-slim', 'alpine']
        app: ['node']
        version: ['18', '20', '22', '23']

    steps:
    - uses: docker/setup-qemu-action@v3
    - uses: docker/setup-buildx-action@v3

    - name: Check ${{ matrix.app }}:${{ matrix.version }}-${{ matrix.suite }}
      run: |
        docker run --rm --platform linux/loong64 ghcr.io/${{ github.repository_owner }}/${{ matrix.app }}:${{ matrix.version }}-${{ matrix.suite }} node --version

  check-redis:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        suite: ['trixie', 'alpine']
        app: ['redis']
        version: ['7.2', '7.4']

    steps:
    - uses: docker/setup-qemu-action@v3
    - uses: docker/setup-buildx-action@v3

    - name: Check ${{ matrix.app }}:${{ matrix.version }}-${{ matrix.suite }}
      run: |
        docker run --rm --platform linux/loong64 ghcr.io/${{ github.repository_owner }}/${{ matrix.app }}:${{ matrix.version }}-${{ matrix.suite }} redis-server --version

  check-postgres:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        suite: ['trixie', 'alpine']
        app: ['postgres']
        version: ['13', '14', '15', '16', '17']

    steps:
    - uses: docker/setup-qemu-action@v3
    - uses: docker/setup-buildx-action@v3

    - name: Check ${{ matrix.app }}:${{ matrix.version }}-${{ matrix.suite }}
      run: |
        docker run --rm --platform linux/loong64 ghcr.io/${{ github.repository_owner }}/${{ matrix.app }}:${{ matrix.version }}-${{ matrix.suite }} psql --version

  check-mariadb:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        suite: ['trixie']
        app: ['mariadb']
        version: ['11.4', '11.8']

    steps:
    - uses: docker/setup-qemu-action@v3
    - uses: docker/setup-buildx-action@v3

    - name: Check ${{ matrix.app }}:${{ matrix.version }}-${{ matrix.suite }}
      run: |
        docker run --rm --platform linux/loong64 ghcr.io/${{ github.repository_owner }}/${{ matrix.app }}:${{ matrix.version }}-${{ matrix.suite }} mariadb --version